# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addcourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
                ('courseid', models.CharField(max_length=10)),
                ('prof', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
    ]
