# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
