# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-07 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0002_auto_20170217_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(max_length=30)),
                ('commenttext', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewcourse.addcourse')),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
