# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-07 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenttext',
            field=models.TextField(max_length=200),
        ),
    ]
