# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-07 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0004_auto_20170307_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='viewcourse.addcourse'),
        ),
    ]
