# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-14 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0007_auto_20170313_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcourse',
            name='prof',
        ),
    ]
