# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0011_auto_20170319_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='ratingCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpfulness', models.DecimalField(decimal_places=2, max_digits=3)),
                ('clarity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('easiness', models.DecimalField(decimal_places=2, max_digits=3)),
                ('textbook', models.DecimalField(decimal_places=2, max_digits=3)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Criteria', to='viewcourse.professor')),
            ],
        ),
    ]
