# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0012_ratingcriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingcriteria',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Criteria_Course', to='viewcourse.addcourse'),
        ),
        migrations.AlterField(
            model_name='ratingcriteria',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Criteria_Professor', to='viewcourse.professor'),
        ),
    ]
