# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0013_auto_20170321_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingcriteria',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterias', to='viewcourse.addcourse'),
        ),
    ]
