# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0016_auto_20170325_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='account',
        ),
    ]
