# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0018_auto_20170325_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
