# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0020_auto_20170325_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
