# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0022_auto_20170326_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.CharField(max_length=30),
        ),
    ]
