# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0023_auto_20170326_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.CharField(max_length=20)),
                ('cid', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='viewcourse.account')),
            ],
        ),
    ]
