# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0024_account_vote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account_vote',
            new_name='vote',
        ),
    ]
