# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0028_auto_20170331_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('commentid', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='viewcourse.account')),
            ],
        ),
    ]
