# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0030_auto_20170331_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='commentid',
            field=models.IntegerField(),
        ),
    ]
