# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-02 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewcourse', '0031_auto_20170331_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
        migrations.AddField(
            model_name='course',
            name='coursetitle',
            field=models.CharField(default=b'', max_length=40),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseid',
            field=models.CharField(max_length=20),
        ),
    ]
